version: "3.8"

networks:
  default:
    name: colosseo-network-local

services:
#  colosseo-nginx:
#    container_name: colosseo-nginx
#    build:
#      Dockerfile: Dockerfile
#      context: ./nginx
#    image: mhlee1994/colosseo-nginx
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx/conf.d:/etc/nginx/conf.d
#    depends_on:
#      - colosseo-app

  colosseo-db:
    image: mhlee1994/colosseo-db
    container_name: colosseo-db
    build:
      dockerfile: Dockerfile
      context: ./database
    environment:
      - MYSQL_DATABASE=colosseo
      - MYSQL_ROOT_PASSWORD=abc123
    volumes:
      - ./database/config:/etc/mysql/conf.d
    ports:
      - '3306:3306'

#  colosseo-app:
#    container_name: colosseo-app
#    build:
#      Dockerfile: Dockerfile
#      context: .
#    image: mhlee1994/colosseo-app
#    volumes:
#      - /Users/imuhyeon/dev/project-logs/sp/logs:/tmp/logs
#    ports:
#      - "8888:8888"
#    depends_on:
#      - colosseo-db
#      - colosseo-redis
#    restart: always

  colosseo-redis:
    image: mhlee1994/colosseo-redis
    container_name: colosseo-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    ports:
      - '6379:6379'

  colosseo-prometheus:
    image: mhlee1994/colosseo-prometheus
    container_name: colosseo-prometheus
    build:
      dockerfile: Dockerfile
      context: ./prometheus
    ports:
      - '9090:9090'
    volumes:
      - type: bind
        source: ./prometheus/config.yaml
        target: /etc/prometheus/prometheus.yml
        read_only: true

  colosseo-grafana:
    image: mhlee1994/colosseo-grafana
    container_name: colosseo-granfana
    build:
      dockerfile: Dockerfile
      context: ./grafana
    ports:
      - '3000:3000'
    links:
      - colosseo-prometheus