springdoc:
  # Disabling the swagger-ui
  swagger-ui:
    path: /swagger-ui
    enabled: true
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
    enabled: true

server:
  port: 8888
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  cache:
    type: redis
#  config:
#    activate:
#      on-profile: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/colosseo
#    url: jdbc:mysql://colosseo-db:3306/colosseo
    username: root
    password: abc123
  devtools:
    livereload:
      enable: true
  jpa:
    properties:
      hibernate:
        ddl-auto: validate
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100 # n+1 문제 해결 방법 중 하나
    open-in-view: false
    generate-ddl: true

  data:
    redis:
#      host: localhost
      host: localhost
      port: 6379

#  security:
#    oauth2:
#      client:
#        registration:
#          naver:
#            client-id: 3uo_IvrPRNr_lSPyqAIy
#            client-secret: LuzH2WByJH


jwt:
  auth:
    key: auth
  security:
    header: Authorization
    key: 7dcDetdY3vTOdQG9m5bgaaNgFg/UbWJqwUFx0HYD0zE6Ljl0lo3E63Df2AL+ujsHckr/YcGLBPMIug7M+c2igQ==

mail:
  smtp:
    port: 465
    auth: true
    starttls:
      required: true
      enable: true
    socketFactory:
      class: javax.net.ssl.SSLSocketFactory
      fallback: false
      port: 465

AdminMail:
  id: dissgo12@gmail.com
  password: gknwucnmlvcfncnh

