management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

springdoc:
  # Disabling the swagger-ui
  swagger-ui:
    path: /swagger-ui
    enabled: true
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
    enabled: true

server:
  port: 8888
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  config:
    activate:
      on-profile: local
  cache:
    type: redis
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/colosseo?useSSL=false
    username: root
    password: abc123
  devtools:
    livereload:
      enable: true
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100 # n+1 문제 해결 방법 중 하나
    open-in-view: false
    generate-ddl: true

  data:
    redis:
      host: localhost
#      host: colosseo-redis
      port: 6379

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 2840b346775ba2737bbef139ad5b5aac
            client-secret: 5zpk5X8OcB0yfLL9NTDpbXbrbX0xF93Q
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8888/oauth2/callback/kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: Kakao
          naver:
            client-id: 3uo_IvrPRNr_lSPyqAIy
            client-secret: LuzH2WByJH
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8888/oauth2/callback/naver
            scope:
              - name
              - email
              - nickname
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
jwt:
  auth:
    key: auth
  security:
    header: Authorization
    key: 7dcDetdY3vTOdQG9m5bgaaNgFg/UbWJqwUFx0HYD0zE6Ljl0lo3E63Df2AL+ujsHckr/YcGLBPMIug7M+c2igQ==

mail:
  smtp:
    port: 465
    auth: true
    starttls:
      required: true
      enable: true
    socketFactory:
      class: javax.net.ssl.SSLSocketFactory
      fallback: false
      port: 465

AdminMail:
  id: dissgo12@gmail.com
  password: gknwucnmlvcfncnh

